In [49]:
from Supplements import *
from sklearn.model_selection import train_test_split

In [50]:
dataset = 'loan_data_set.csv'
data = pd.read_csv(dataset, header=0)

processed_output = data_processing(data)
data = processed_output[0]
X = data.iloc[:, 0:data.shape[1] - 1]
X = X.sample(frac = 1)
X.reset_index(inplace=True, drop=True)
y_original = list(data.iloc[:, -1])
scaled_income = processed_output[1].scale_[0] * (5000 - processed_output[1].data_min_[0])

X, y = data_manipulation(X, y_original)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33)
X_train.reset_index(inplace=True, drop=True)
X_test.reset_index(inplace=True, drop=True)

X_train

['Married', 'Loan_Status', 'Dependents', 'Education', 'Self_Employed', 'Property_Area', 'Gender']
['ApplicantIncome', 'CoapplicantIncome', 'LoanAmount', 'Loan_Amount_Term', 'Credit_History']

,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Gender_Male,Married_Yes,Dependents_1,Dependents_2,Dependents_3+,Education_Not Graduate,Self_Employed_Yes,Property_Area_Semiurban,Property_Area_Urban
0,0.126976,0.000000,0.301184,0.72973,0.0,1,0,0,0,0,0,1,0,1
1,0.068967,0.135798,0.421320,0.72973,1.0,1,1,0,0,0,0,0,1,0
2,0.104094,0.000000,0.340102,0.72973,1.0,1,0,0,0,0,0,0,0,1
3,0.020408,0.086710,0.142132,0.72973,0.0,1,1,0,0,0,1,0,0,1
4,0.041558,0.130508,0.395939,0.72973,1.0,1,1,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
316,0.020853,1.000000,0.137056,0.72973,1.0,1,0,0,0,0,0,0,0,1
317,0.040198,0.000000,0.145516,0.72973,1.0,0,0,0,0,0,1,0,0,0
318,0.054471,0.036321,0.252115,0.72973,1.0,1,1,1,0,0,1,0,0,1
319,0.036425,0.000000,0.175973,0.72973,1.0,1,1,0,0,1,1,0,0,0
320,0.039369,0.096049,0.252115,0.72973,1.0,1,1,1,0,0,0,0,0,1

In [60]:
class NN:
    def __init__(self):
        self.n_hidden_layers = 1
        self.models = {}
    
    def learn_linear_model(self, X, y):
        pass
    
    def learn_layer_model(self, X, y, layer_id=0):
        X_output = pd.DataFrame()
        for j in range(len(self.models[layer_id])):
            self.models[layer_id][j].learn_without_sade(X, y, M=[0], learner='fumalik')
            X_output[j] = [v if v > 0 else 0 for v in self.models[layer_id][j].predict(X, y)[3]]
        return X_output
        
    def learn(self, X, y, n_hidden_layers=[[2]]):
        if len(n_hidden_layers) > 1:
            raise VaueError('invalid input: n_hidden_layers')
        
        self.models[0] = [LinearClassificationLearnerLoan()]*n_hidden_layers[0][0]
        self.models[1] = [LinearClassificationLearnerLoan()]
        
        X_new = self.learn_layer_model(X, y, layer_id=0)
        self.learn_layer_model(X_new, y, layer_id=1)

In [71]:
model = NN()
model.learn(X_train.iloc[:40, :], y_train[:40])

starting the check
found unsat
size of core: 12
found sat
learned parameters
[95.58201639436446, -100.0, -29.90398124887277, 27.1841036809981, -27.376346332274814, -58.37457254442536, 1.8328158571489261, -19.963014295129987, 15.460557335822081, 1.3566809562205853, 2.7772379252269874, -38.805548786978484, 3.700151150622456, -0.5954867575587595, -16.836035497833688]
training accuracy: 0.875
starting the check
found unsat
size of core: 10
found unsat
size of core: 9
found unsat
size of core: 10
found unsat
size of core: 8
found sat
learned parameters
[100.0, -100.0, -29.872987821049414, 26.595294776453105, -27.079091430154957, -63.085779454571565, 1.957255793425724, -24.97357147547687, 15.415627536442958, 6.449974110687955, 7.83512252875742, -38.62545218099506, 3.6538622458792553, -0.5198093747286455, -16.70016691251479]
training accuracy: 0.925
starting the check
found unsat
size of core: 2
found unsat
size of core: 2
found unsat
size of core: 3
found sat
learned parameters
[-2.0, 0.0, 3.8219305754068227]
training accuracy: 0.925