In [1]:
from Supplements import *

In [4]:
dataset = 'loan_data_set.csv'
data = pd.read_csv(dataset, header=0)

processed_output = data_processing(data)
data = processed_output[0]
X = data.iloc[:, 0:data.shape[1] - 1]
X = X.sample(frac = 1)
X.reset_index(inplace=True, drop=True)
y_original = list(data.iloc[:, -1])
scaled_income = processed_output[1].scale_[0] * (5000 - processed_output[1].data_min_[0])

X, y = data_manipulation(X, y_original)
X

['Married', 'Loan_Status', 'Dependents', 'Education', 'Self_Employed', 'Property_Area', 'Gender']
['ApplicantIncome', 'CoapplicantIncome', 'LoanAmount', 'Loan_Amount_Term', 'Credit_History']

,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Gender_Male,Married_Yes,Dependents_1,Dependents_2,Dependents_3+,Education_Not Graduate,Self_Employed_Yes,Property_Area_Semiurban,Property_Area_Urban
0,0.027557,0.000000,0.062606,0.729730,1.0,0,0,0,0,0,0,0,0,0
1,0.075782,0.000000,0.184433,0.729730,0.0,1,0,0,0,0,0,0,0,0
2,0.025813,0.000000,0.091371,1.000000,0.0,1,0,0,0,0,0,0,1,0
3,0.036277,0.064072,0.197970,0.729730,1.0,1,1,0,1,0,1,0,0,1
4,0.045145,0.106392,0.350254,0.729730,0.0,1,1,0,1,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
475,0.055139,0.084080,0.221658,0.324324,1.0,0,1,1,0,0,0,0,1,0
476,0.054620,0.000000,0.153976,0.729730,1.0,1,1,0,1,0,0,0,0,1
477,0.047619,0.073884,0.221658,0.729730,1.0,1,0,0,0,0,0,0,0,0
478,0.028139,0.069155,0.226734,0.729730,1.0,1,1,0,0,0,0,0,1,0
479,0.040928,0.000000,0.027073,0.189189,1.0,1,1,0,0,0,0,1,1,0

In [38]:
class NN:
    def __init__(self):
        self.n_hidden_layers = 1
        self.models = {}
    
    def learn_linear_model(self, X, y):
        pass
    
    def learn_layer_model(self, X, y, layer_id=0):
        X_output = pd.DataFrame()
        for j in range(len(self.models[layer_id])):
            self.models[layer_id][j].learn_without_sade(X, y, M=[0], learner='fumalik')
            X_output[j] = [v if v > 0 else 0 for v in self.models[layer_id][j].predict(X, y)[3]]
        return X_output
        
    def learn(self, X, y, n_hidden_layers=[[2]]):
        if len(n_hidden_layers) > 1:
            raise VaueError('invalid input: n_hidden_layers')
        
        self.models[0] = [LinearClassificationLearnerLoan()]*n_hidden_layers[0][0]
        self.models[1] = [LinearClassificationLearnerLoan()]
        
        self.learn_layer_model(X, y, layer_id=0)

In [39]:
model = NN()
model.learn(X.iloc[:40, :], y[:40])

starting the check
found unsat
size of core: 13
found sat
learned parameters
[1.2461605270785991, -100.0, -27.91858762378921, -22.37543672754417, 6.812195184658279, -2.2885789758412534, 5.936186731210171, -0.2143657965893162, -3.314100517070075, -4.293950522262569, 1.8054159830786844, -0.6210281315436318, 11.602204010987009, 1.266224473417288, 7.904757166943969]
training accuracy: 0.975
starting the check
found unsat
size of core: 12
found unsat
size of core: 12
found sat
learned parameters
[6.626410393958782, -99.41007155298617, 2.3229584021662126, -13.64759844067529, 4.689252067120708, -7.4544151700109405, 6.297887748120281, 4.235281057418045, -6.031935972638257, -5.531851002159538, -1.9390164615443912, -2.1074228483676336, 9.387556972037144, -1.4973101902775183, 1.7129174709697483]
training accuracy: 0.975
            0          1
0    0.000000   0.000000
1    0.448405   6.295590
2   10.634987  12.303156
3    2.794086   1.041417
4    0.227909   7.741654
5    1.731239  13.951085
6    0.000000   0.000000
7    7.776860   7.339647
8    0.000000   0.000000
9    0.227909   1.000000
10   1.727568   2.499037
11   0.000000   0.000000
12  15.351391  18.570249
13   3.268349   1.000000
14   0.000000   0.000000
15   0.000000   0.000000
16   0.000000   0.000000
17   0.227909   2.120577
18   0.000000   0.000000
19   2.466395   1.000000
20   0.227909  10.943574
21   0.227909   2.779230
22   0.000000   0.000000
23   0.000000   0.000000
24   0.000000   0.000000
25   1.213069   1.000000
26   0.000000   0.000000
27   0.227909   2.332195
28   0.227909   1.000000
29   1.422455   5.200450
30   0.000000   0.000000
31   0.000000   1.783119
32  15.254929  11.234104
33   0.584041   9.127677
34   2.332594   6.564201
35   0.000000   4.242294
36   0.227909   4.542703
37   0.227909   1.000000
38   0.227909   1.000000
39   0.000000   0.000000